version: "3.9"
services:
  orchestrator:
    build: ./orchestrator
    stdin_open: true 
    tty: true        
    ports:
      - "1000:80"
      - "2000:22"
  webui:
    build: ./webui
    stdin_open: true 
    tty: true 
    ports:
     - "1001:80"
     - "2001:22"
  worker:
    build: ./worker
    stdin_open: true 
    tty: true 
    ports:
     - "1002:80"
     - "2002:22"
